# Generated by Django 3.2.16 on 2024-07-19 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20240719_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='descriptoin',
            new_name='description',
        ),
    ]
